services:
  - type: web
    name: basketball-shot-predictor
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools wheel
      python -m pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /api/status
